export const LINKS = [
  {
    href: "https://ray.so/",
    icon: "✧",
    title: "Ray.so",
    tag: "Design",
    description: "Turn code snippets into gorgeous visuals with minimal effort.",
  },
  {
    href: "https://www.figma.com/community",
    icon: "◼︎",
    tag: "UI",
    title: "Figma Community",
    description: "Explore UI kits, components, and design inspiration from creators.",
  },
  {
    href: "https://fonts.google.com/",
    icon: "Aa",
    tag: "Typography",
    title: "Google Fonts",
    description: "Discover clean typefaces and pairings for modern interfaces.",
  },
  {
    href: "https://coolors.co/",
    icon: "◌",
    tag: "Color",
    title: "Coolors",
    description: "Generate palettes that feel calm, cohesive, and contemporary.",
  },
  {
    href: "https://www.are.na/",
    icon: "⎔",
    tag: "Moodboards",
    title: "Are.na",
    description: "Collect and connect ideas—like a visual thinking space.",
  },
  {
    href: "https://musicforprogramming.net/",
    icon: "♪",
    tag: "Playlist",
    title: "Music for Programming",
    description: "Long-form ambient mixes for focus, flow, and deep work.",
  },
  {
    href: "https://www.notion.so/templates",
    icon: "▦",
    tag: "Templates",
    title: "Notion Templates",
    description: "Beautiful, practical systems for notes, tasks, and projects.",
  },
  {
    href: "https://vercel.com/templates",
    icon: "△",
    tag: "Next.js",
    title: "Vercel Templates",
    description: "High-quality starter templates for fast, polished deployments.",
  },
  {
    href: "https://linear.app/",
    icon: "⟡",
    tag: "Productivity",
    title: "Linear",
    description: "A crisp, modern issue tracker with excellent UI discipline.",
  },
] as const;
